/* DO NOT EDIT: this file was automatically generated by airtable-ts-codegen */
/* eslint-disable */
import type { Item, Table } from 'airtable-ts';

export interface Service extends Item {
  id: string,
  slug: string | null, // Original field: "Slug"
  title: string | null, // Original field: "Title"
  titleEnglish: string | null, // Original field: "Title English"
  content: string | null, // Original field: "Content"
  contentEnglish: string | null, // Original field: "Content English"
  sortKey: number | null, // Original field: "Sort Key"
  assignee: string | null, // Original field: "Assignee"
  status: string | null, // Original field: "Status"
  image: string[] | null, // Original field: "Image"
}

export const servicesTable: Table<Service> = {
  name: 'Services',
  baseId: 'appl3TN9b8Cik8K34',
  tableId: 'tblhFs46yyTpwURCT',
  mappings: {
    slug: 'fldhFbPxoxODk2eV2', // Original field: "Slug"
    title: 'fldqOMX9T1aTBPfbm', // Original field: "Title"
    titleEnglish: 'fldFsFvi5Po2D81e4', // Original field: "Title English"
    content: 'fldbyqIZdntp3RoJR', // Original field: "Content"
    contentEnglish: 'flddOsPQzQ2uFMnkL', // Original field: "Content English"
    sortKey: 'fldoIwqliPidkxf7e', // Original field: "Sort Key"
    assignee: 'fldTa2l4OugZgn8Cv', // Original field: "Assignee"
    status: 'fldP6fYXNGbA0MwLM', // Original field: "Status"
    image: 'fldpYgdovRN7zimor', // Original field: "Image"
  },
  schema: {
    slug: 'string | null',
    title: 'string | null',
    titleEnglish: 'string | null',
    content: 'string | null',
    contentEnglish: 'string | null',
    sortKey: 'number | null',
    assignee: 'string | null',
    status: 'string | null',
    image: 'string[] | null',
  },
};