@BASE_ID={{$dotenv AIRTABLE_BASE_ID}}
@BASE_URL=https://api.airtable.com/v0/bases
@API_KEY={{$dotenv AIRTABLE_API_KEY}}
@WEBHOOK_URL={{BASE_URL}}/{{BASE_ID}}/webhooks
@SERVICE_TABLE_ID=tblhFs46yyTpwURCT

### Insert
POST {{WEBHOOK_URL}}
Authorization: Bearer {{API_KEY}}
Content-Type: application/json

{
  "notificationUrl": "https://familogue.ca/api/revalidate",
  "specification": {
    "options": {
      "filters": {
        "dataTypes": [
          "tableData"
        ],
        "recordChangeScope": "{{SERVICE_TABLE_ID}}"
      }
    }
  }
}

### List
GET {{WEBHOOK_URL}}
Authorization: Bearer {{API_KEY}}
Content-Type: application/json

### Delete
DELETE {{WEBHOOK_URL}}/achs7NtowxGAeXW56
Authorization: Bearer {{API_KEY}}
Content-Type: application/json

### Test webhook
POST https://familogue.ca/api/revalidate

###
POST http://localhost:3000/api/revalidate